# Generated by Django 5.2.5 on 2025-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
